server:
  port: 3000
  host: "0.0.0.0"

logging:
  level: "info,api_gateway=info,tower_http=info"

gateway:
  routes:
    - id: "user_service"
      uri: "${USER_SERVICE_URI}"
      predicates:
        - Path: "/api/users/**"

    - id: "game_service"
      uri: "${GAME_SERVICE_URI}"
      predicates:
        - Path: "/api/games/**"

    - id: "auth_service"
      uri: "${AUTH_SERVICE_URI}"
      predicates:
        - Path: "/api/auth/**"

    - id: "websocket_service"
      uri: "${WEBSOCKET_SERVICE_URI}"
      predicates:
        - Path: "/ws/**"